language: python
python:
  - '2.7'

# Blacklist
branches:
  except:
    - gh-pages

# Limit clone depth, does it speed up the build?
git:
  depth: false
  
# Cache PlatformIO packages using Travis CI container-based infrastructure
#sudo: required
sudo: false
cache:
    directories:
        - "~/.platformio"
        - "$HOME/.cache/pip/"
        - $CACHED

env:
  global:
    - REVIEWDOG_VERSION="0.9.11"
    # cppcheck
    - VERSION=1.84
    - NAMEVER=cppcheck-${VERSION}
    - CACHED=$HOME/cached 
    # arduino scripts
    - CONFIG_KEYWORDS_NAME="Travis CI - Keywords Bot"
    - CONFIG_KEYWORDS_EMAIL=travis@example.com
    - CONFIG_KEYWORDS_BRANCH=master
    - CONFIG_VERSION_NAME="Travis CI - Version Bot"
    - CONFIG_VERSION_EMAIL="$CONFIG_KEYWORDS_EMAIL"
    - CONFIG_VERSION_BRANCH="$CONFIG_KEYWORDS_BRANCH"
    - CONFIG_CHANGELOG_NAME="Travis CI - Changelog Bot"
    - CONFIG_CHANGELOG_EMAIL="$CONFIG_KEYWORDS_EMAIL"
    - CONFIG_CHANGELOG_BRANCH="$CONFIG_KEYWORDS_BRANCH"
  matrix:
    # add examples here and define which boards should be tested (only compile test)
    - PLATFORMIO_CI_SRC=examples/ABC/ABC.ino TESTBOARD=arduino_avr

matrix:
  fast_finish: true

install:
    - python --version
    ## cppcheck
    - source <(curl -SLs https://raw.githubusercontent.com/TestGithubIntegration/mfrc522/add_gitattribute/.build_cppcheck.sh)
    ############
    - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.10 bash)"
    #############
    - go get -u github.com/golang/dep/...
    - go get github.com/client9/misspell/cmd/misspell
    - mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
    - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ~/bin/reviewdog && chmod +x ~/bin/reviewdog
    ########
    - pip install -U platformio

script:
    #- bash ./.build.sh
    - source <(curl -SLs https://raw.githubusercontent.com/TestGithubIntegration/mfrc522/add_gitattribute/.cppcheck.sh)
   #######################
    #- platformio ci --lib=. --board=uno 
    - reviewdog -conf=.reviewdog.yml -reporter=github-pr-check

#after_success:
deploy:
    - provider: script
      script: source <(curl -SLs https://raw.githubusercontent.com/Rotzbua/test/master/deploy_keywords.sh)
      on:
        #branch: dev
        branch: master
        #all_branches: true
    - provider: script
      script: source <(curl -SLs https://raw.githubusercontent.com/Rotzbua/test/master/deploy_version.sh)
      on:
        branch: master
    - provider: script
      script: source <(curl -SLs https://raw.githubusercontent.com/Rotzbua/test/master/deploy_changelog.sh)
      on:
        branch: master
